routes/web.php
<?php

use App\Http\Controllers\DadosImportacaoController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\EscalaController;
use App\Http\Controllers\FaturamentoController;
use App\Http\Controllers\FinanceiroController;
use App\Http\Controllers\MigrationController;
use App\Http\Controllers\PeriodoEscalaController;
use App\Http\Controllers\VagasController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

//Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/', [HomeController::class, 'index'])->name('index');
Route::get('/home', [HomeController::class, 'home'])->name('home');
Route::get('/admin/home', [HomeController::class, 'adminHome'])->name('admin.home')->middleware('is_admin');

Route::get('/realizar-cadastro', [EscalaController::class, 'index'])->name('realizar-cadastro');

Route::get('dados-importacao', [DadosImportacaoController::class, 'index']);
Route::get('importar-arquivo-financeiro', [DadosImportacaoController::class, 'importarArquivoFinanceiro'])->name('dados-importacao.importar-arquivo-financeiro')->middleware('auth');
Route::post('dados-importacao', [DadosImportacaoController::class, 'importarArquivo'])->name('importar-arquivo');
Route::post('store-importar-arquivo-financeiro', [DadosImportacaoController::class, 'storeImportarArquivoFinanceiro'])->name('store-importar-arquivo-financeiro')->middleware('auth');

Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard')->middleware('auth');
Route::get('/dashboard/dados', [DashboardController::class, 'dados'])->name('dashboard.dados')->middleware('auth');

Route::get('financeiro/dados', [FinanceiroController::class, 'dados'])->name('financeiro.dados')->middleware('auth');
Route::resource('financeiro', FinanceiroController::class);
Route::get('/financeiro/{id}', [FinanceiroController::class, 'show'])->name('financeiro.show');

Route::get('faturamento/dados', [FaturamentoController::class, 'dados'])->name('faturamento.dados')->middleware('auth');
Route::resource('faturamento', FaturamentoController::class)->middleware('auth');
Route::get('/faturamento/{id}', [FaturamentoController::class, 'show'])->name('faturamento.show');
Route::get('/select2-dados-ajax', [FaturamentoController::class, 'select2DadosAjax'])->name('faturamento.select2-dados-ajax')->middleware('auth');
Route::post('/associar-entregador', [FaturamentoController::class, 'associarEntregador'])->name('faturamento.associar-entregador')->middleware('auth');

Route::get('/migration/v1', [MigrationController::class, 'v1']);

Route::get('/agendar', [EscalaController::class, 'agendar'])->name('escala.agendar');
Route::get('/agendar/{codigo}/{areaEntregaIdGuid}', [EscalaController::class, 'agendar']);
Route::get('/agendar/{codigo}/{areaEntregaIdGuid}/{cpf}', [EscalaController::class, 'agendar']);
Route::post('/agendar', [EscalaController::class, 'storeAgendar'])->name('escala.store-agendar');
Route::post('/atualizar-agendamento', [EscalaController::class, 'storeAtualizarAgendamento'])->name('escala.store-atualizar-agendamento');

/*Route::get('/escala/cadastrar-salvador-regular', [EscalaController::class, 'cadastrarSalvadorRegular'])->name('escala.cadastrar-salvador-regular');
Route::get('/escala/cadastrar-salvador-regular/{codigo}', [EscalaController::class, 'cadastrarSalvadorRegular']);
Route::get('/escala/cadastrar-salvador-regular/{codigo}/{cpf}', [EscalaController::class, 'cadastrarSalvadorRegular']);
Route::post('/escala/store-cadastrar-salvador-regular', [EscalaController::class, 'storeCadastrarSalvadorRegular'])->name('escala.store-cadastrar-salvador-regular');
Route::post('/escala/store-atualizar-salvador-regular', [EscalaController::class, 'storeAtualizarSalvadorRegular'])->name('escala.store-atualizar-salvador-regular');
*/
Route::get('/escala', [EscalaController::class, 'index'])->middleware('auth');
Route::get('/escala/por-entregador', [EscalaController::class, 'porEntregador'])->name('escala.por-entregador')->middleware('auth');
Route::get('/escala/por-area', [EscalaController::class, 'porArea'])->name('escala.por-area')->middleware('auth');
Route::get('/escala/dados', [EscalaController::class, 'dados'])->name('escala.dados')->middleware('auth');
Route::get('/escala/dados-por-area', [EscalaController::class, 'dadosPorArea'])->name('escala.dados-por-area')->middleware('auth');

Route::get('/escala/{escalaId}', [EscalaController::class, 'visualizar'])->name('escala.visualizar')->middleware('auth');
Route::get('/escala/{pracaId}/{periodoEscalaId}/{areaEntregaId}/{data?}', [EscalaController::class, 'visualizarPorArea'])->name('escala.visualizar-por-area')->middleware('auth');
Route::get('/escala/editar/{escala}', [EscalaController::class, 'editar'])->name('escala.editar')->middleware('auth');
Route::put('/escala/{escala}', [EscalaController::class, 'atualizar'])->name('escala.atualizar')->middleware('auth');
Route::delete('/escala/{escalaId}', [EscalaController::class, 'excluir'])->name('escala.excluir')->middleware('auth');

Route::get('/periodo-escala', [PeriodoEscalaController::class, 'index'])->name('periodoEscala.index')->middleware('auth');
Route::get('/periodo-escala/cadastrar', [PeriodoEscalaController::class, 'cadastrar'])->name('periodoEscala.cadastrar')->middleware('auth');
Route::post('/periodo-escala', [PeriodoEscalaController::class, 'guardar'])->name('periodoEscala.guardar');
Route::get('/periodo-escala/{periodoEscala}/editar', [PeriodoEscalaController::class, 'editar'])->name('periodoEscala.editar');
Route::put('/periodo-escala/{periodoEscala}', [PeriodoEscalaController::class, 'atualizar'])->name('periodoEscala.atualizar')->middleware('auth');
Route::get('/periodo-escala/dados', [PeriodoEscalaController::class, 'dados'])->name('periodoEscala.dados')->middleware('auth');
Route::delete('/periodo-escala/{periodoEscala}', [PeriodoEscalaController::class, 'excluir'])->name('periodoEscala.excluir')->middleware('auth');
Route::get('/periodo-escala/{periodoEscala}', [PeriodoEscalaController::class, 'visualizar'])->name('periodoEscala.visualizar')->middleware('auth');

Route::get('/vagas/geral/{periodoEscalaId?}/{data?}', [VagasController::class, 'geral'])->name('vagas.geral')->middleware('auth');
Route::get('/vagas/listagem/{periodoEscalaId?}', [VagasController::class, 'listagem'])->name('vagas.listagem')->middleware('auth');
Route::get('/vagas/editar/{periodoEscalaId}/{areaEntregaId}', [VagasController::class, 'editar'])->name('vagas.editar')->middleware('auth');
Route::put('/vagas/{periodoEscalaId}/{areaEntregaId}', [VagasController::class, 'atualizar'])->name('vagas.atualizar')->middleware('auth');
Route::get('/vagas/dados/{periodoEscalaId?}', [VagasController::class, 'dados'])->name('vagas.dados')->middleware('auth');

/*
GET           /users/{user}               show    users.show

Verb          Path                        Action  Route Name
GET           /users                      index   users.index
GET           /users/create               create  users.create
POST          /users                      store   users.store
GET           /users/{user}/edit          edit    users.edit
PUT|PATCH     /users/{user}               update  users.update
DELETE        /users/{user}               destroy users.destroy
*/
/*
$routeView = route('escala.visualizar', $row['id']);
$routeEdit = route('escala.atualizar', $row['id']);
$routeDelete = route('escala.excluir', $row['id']);
*/

app/Http/Controllers/FinanceiroController.php
<?php

namespace App\Http\Controllers;

use App\Models\Banco;
use App\Models\DadosBancario;
use App\Models\Faturamento;
use Illuminate\Http\Request;
use DataTables;
use Exception;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\DB;
use PDOException;

class FinanceiroController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth')->except(['show', 'create', 'store']);
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('financeiro.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\DadosBancario  $dadosBancario
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $dadosBancario = DadosBancario::find(Crypt::decrypt($id));
        return view('financeiro.show', ["dadosBancario" => $dadosBancario]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //U2FsdmFkb3I=
        //QXJhY2FqdQ==
        // response('Requisição inválida', 400)
        $municipio = base64_decode(request()->get('mn'));
        if($municipio != "Salvador" && $municipio != "Aracaju" ) {
            return response('Requisição inválida', 400);
        }
        $bancos = Banco::all();
        return view('financeiro.create', compact('bancos'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $municipio = base64_decode(request()->get('mn'));
        if($municipio != "Salvador" && $municipio != "Aracaju" ) {
            return response('Requisição inválida', 400);
        }
        $request->validate([
            'nome' => 'required',
            'cpf' => 'required|cpf',
            'pix' => 'required',
            'agencia' => 'required',
            'conta' => 'required',
            'banco_id' => 'required'
        ],
        [
            'required' => 'Campo :attribute obrigatório',
            'cpf' => 'CPF inválido'
        ]);

        try {
            $dadosBancarioPost = $request->all();
            $dadosBancarioPost['municipio'] = $municipio;
            if(DadosBancario::where('cpf', $dadosBancarioPost['cpf'])->exists()) {
                return redirect()->back()->withInput()->with('error', "CPF já cadastrado");
            }
            $dadosBancario = DadosBancario::create($dadosBancarioPost);

            Faturamento::where('entregador', $dadosBancario->nome)
                ->where('praca', $dadosBancario->municipio)
                ->update(['dados_bancario_id' => $dadosBancario->id]);

            return redirect()
                ->route('financeiro.show', Crypt::encrypt($dadosBancario->getKey()))
                ->with('success', 'Dados cadastrados com sucesso!');
        } 
        catch (PDOException $ex) {
          if ($ex->getCode() == 23505)
                return redirect()->back()->withInput()->with('error', 'Estes dados já foram cadastrados!');    
            return redirect()->back()->withInput()->with('error', $ex->getMessage());
        } catch (Exception $ex) {
            return redirect()->back()->withInput()->with('error', $ex->getMessage());
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\DadosBancario  $dadosBancario
     * @return \Illuminate\Http\Response
     */
    public function edit(DadosBancario $financeiro)
    {
        $dadosBancario = $financeiro;
        $bancos = Banco::all();
        return view('financeiro.edit', compact('dadosBancario', 'bancos'));
    }
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\DadosBancario  $dadosBancario
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, DadosBancario $financeiro)
    {
        $request->validate([
            'municipio' => 'required',
            'nome' => 'required',
            'cpf' => 'required|cpf',
            'pix' => 'required',
            'agencia' => 'required',
            'conta' => 'required',
            'banco_id' => 'required'
        ],
        [
            'required' => 'Campo :attribute obrigatório',
            'cpf' => 'CPF inválido'
        ]);

        try {
            $dadosBancarioPost = $request->all();
            if($financeiro->getOriginal('cpf') != $dadosBancarioPost['cpf'] && DadosBancario::where('cpf', $dadosBancarioPost['cpf'])->exists()) {
                return redirect()->back()->withInput()->with('error', "Já existe um usuário cadastrado com CPF {$dadosBancarioPost['cpf']}!");
            }
            $financeiro->update($dadosBancarioPost);

            Faturamento::where('entregador', $financeiro->nome)
                ->where('praca', $financeiro->municipio)
                ->update(['dados_bancario_id' => $financeiro->id]);

            return redirect()->route('financeiro.index', ['s' => Crypt::encrypt("s3nh4")])
                ->with('success', 'Dados bancário atualizado com sucesso!');
        } 
        catch (PDOException $ex) {
          if ($ex->getCode() == 23505)
                return redirect()->back()->withInput()->with('error', 'Estes dados já foram cadastrados!');    
            return redirect()->back()->withInput()->with('error', $ex->getMessage());
        } catch (Exception $ex) {
            return redirect()->back()->withInput()->with('error', $ex->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\DadosBancario  $dadosBancario
     * @return \Illuminate\Http\Response
     */
    public function destroy(DadosBancario $financeiro)
    {
        $financeiro->delete();

        return redirect()->back()
            ->with('success', 'Conta deletada com sucesso!');
    }

    public function dados()
    {
        //$dadosBancarios = DB::table('dados_bancario');
        
        $model = DadosBancario::with('banco');
        return DataTables::eloquent($model)
            ->addColumn('banco', function (DadosBancario $dadosBancario) {
                return $dadosBancario->banco->nome;
            })
            ->addColumn("action", function($row){
                $routeView = route('financeiro.show', Crypt::encrypt($row['id']));
                $routeEdit = route('financeiro.edit', $row['id']);
                $routeDelete = route('financeiro.destroy', $row['id']);
                $btn = "<a href='{$routeView}' class='btn btn-sm btn-clean btn-icon btn-icon-md'><i class='la la-search text-primary'></i></a>";
                $btn = $btn."<a href='{$routeEdit}' class='edit btn btn-sm btn-clean btn-icon btn-icon-md'><i class='la la-edit text-warning'></i></a>";
                $btn = $btn."<a href='javascript:void(0)' class='delete btn btn-sm btn-clean btn-icon btn-icon-md' data-key='{$row['id']}' data-name='{$row['nome']}' data-url='{$routeDelete}' onclick='proccessDeletion(this)'><i class='la la-trash text-danger'></i></a>";

                return $btn;
            })
            ->rawColumns(['action'])
            ->make(true);
    }
}

resources/views/financeiro/create.blade.php
@extends('layouts.app')

@section('template_title')
    Operador Logístico
@endsection

@section('content')
<div class="kt-subheader   kt-grid__item" id="kt_subheader">
    <div class="kt-container  kt-container--fluid ">
        <div class="kt-subheader__main">
            <h3 class="kt-subheader__title">
                Dados Bancários 
            </h3>
            <span class="kt-subheader__separator kt-hidden"></span>
            <div class="kt-subheader__breadcrumbs">
                <a href="#" class="kt-subheader__breadcrumbs-home"><i class="flaticon2-shelter"></i></a>
                <a class="kt-subheader__breadcrumbs-link">
                    @if(base64_decode(request()->get('mn')) == "Salvador")         
                        <span class="badge badge-success"><i class="la la-check-square"></i> Salvador</span>
                    @else
                        <span class="badge badge-primary"><i class="la la-check-square"></i> Aracaju</span>     
                    @endif                    
                </a>
            </div>
        </div>
    </div>
</div>
<!-- end:: Subheader -->

<!-- begin:: Content -->
<div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">
    @if ($errors->any())
        <div class="alert alert-danger d-flex align-items-center py-4" role="alert">
            <span class="alert-icon icon-help-button lead-3 pr-3"></span>
            <strong>Erros!</strong> 
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{$error}}</li>
                @endforeach
            </ul>
            <span class="c-pointer ml-auto" data-dismiss="alert">
            <span class="fas fa-times lead-1" aria-hidden="true"></span>
            </span>
        </div>
    @endif
    @if ($message = Session::get('error'))
        <div class="alert alert-danger d-flex align-items-center py-4" role="alert">
            <span class="flaticon-warning pr-3"></span><strong>{{ $message }}</strong>
            <span class="c-pointer ml-auto" data-dismiss="alert">
            <span class="fas fa-times lead-1" aria-hidden="true"></span>
            </span>
        </div>
    @endif
    <div class="row">
        <div class="col-12">
            <!--begin::Portlet-->
            <div class="kt-portlet">
                <div class="kt-portlet__head">
                    <div class="kt-portlet__head-label">
                        <h3 class="kt-portlet__head-title">
                            <i class="la la-bank pr-2"></i> Dados bancário
                        </h3>
                    </div>
                </div>
                <form method="post" class="kt-form" action="{{route('financeiro.store', ['mn' => request()->get('mn')])}}">
                    @csrf
                    <div class="kt-portlet__body">
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Nome completo</label>
                                    <input type="text" required class="form-control" name="nome" value="{{ old('nome') }}" placeholder="Digite seu nome completo">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>CPF</label>
                                    <input type="text" required class="form-control cpf" name="cpf" value="{{ old('cpf') }}" placeholder="000.000.000-00">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Pix</label>
                                    <input type="text" required class="form-control" name="pix" value="{{ old('pix') }}" placeholder="Insira o pix">
                                </div>
                            </div>
                        </div>                            
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Banco</label>
                                    <select required class="form-control kt-select2" id="kt_select2_1" name="banco_id">
                                        <option></option>
                                        @foreach ($bancos as $banco)
                                            @if ($banco->id == old('banco_id')))
                                                <option value="{{$banco->id}}" selected="selected">{{$banco->codigo}}-{{$banco->nome}}</option>
                                            @else
                                                <option value="{{$banco->id}}">{{$banco->codigo}}-{{$banco->nome}}</option>
                                            @endif
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Agencia</label>
                                    <input required class="form-control" type="number" name="agencia" value="{{ old('agencia') }}" placeholder="0000">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Conta com digito</label>
                                    <input type="text" required class="form-control conta" name="conta" value="{{ old('conta') }}" placeholder="000000-0">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="kt-portlet__foot">
                        <div class="kt-form__actions">
                            <button type="submit" class="btn btn-success">Cadastrar</button>
                            <a href="{{url("/")}}" class="btn btn-secondary">Voltar</a>
                        </div>
                    </div>
                </form>
                <!--end::Form-->
            </div>
            <!--end::Portlet-->
        </div>
    </div>
</div>
<!-- end:: Content -->
@endsection
@section('template_fastload_js') 
    $(document).ready(function () {
        $('.cpf').mask('000.000.000-00');
        $('.conta').mask('000000000000-0', {reverse: true});
        $(".kt-form").submit(function() {
            $(".conta").unmask();
        });        
        $('#kt_select2_1').select2({
            placeholder: "Selecione o banco"
        });
    });
@endsection

resources/views/financeiro/edit.blade.php
@extends('layouts.app')

@section('template_title')
    Operador Logístico
@endsection

@section('content')
<div class="kt-subheader   kt-grid__item" id="kt_subheader">
    <div class="kt-container  kt-container--fluid ">
        <div class="kt-subheader__main">
            <h3 class="kt-subheader__title">
                Dados Bancários 
            </h3>
            <span class="kt-subheader__separator kt-hidden"></span>
            <div class="kt-subheader__breadcrumbs">
                <a href="#" class="kt-subheader__breadcrumbs-home"><i class="flaticon2-shelter"></i></a>
                <a class="kt-subheader__breadcrumbs-link">
                    @if($dadosBancario->municipio == "Salvador")         
                        <span class="badge badge-success"><i class="la la-check-square"></i> Salvador</span>
                    @else
                        <span class="badge badge-primary"><i class="la la-check-square"></i> Aracaju</span>     
                    @endif                    
                </a>
            </div>
        </div>
    </div>
</div>
<!-- end:: Subheader -->

<!-- begin:: Content -->
<div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">
    @if ($errors->any())
        <div class="alert alert-danger d-flex align-items-center py-4" role="alert">
            <span class="alert-icon icon-help-button lead-3 pr-3"></span>
            <strong>Erros!</strong> 
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{$error}}</li>
                @endforeach
            </ul>
            <span class="c-pointer ml-auto" data-dismiss="alert">
            <span class="fas fa-times lead-1" aria-hidden="true"></span>
            </span>
        </div>
    @endif
    @if ($message = Session::get('error'))
        <div class="alert alert-danger d-flex align-items-center py-4" role="alert">
            <span class="flaticon-warning pr-3"></span><strong>{{ $message }}</strong>
            <span class="c-pointer ml-auto" data-dismiss="alert">
            <span class="fas fa-times lead-1" aria-hidden="true"></span>
            </span>
        </div>
    @endif
    <div class="row">
        <div class="col-12">
            <!--begin::Portlet-->
            <div class="kt-portlet">
                <div class="kt-portlet__head">
                    <div class="kt-portlet__head-label">
                        <h3 class="kt-portlet__head-title">
                            <i class="la la-bank pr-2"></i> Dados bancário
                        </h3>
                    </div>
                </div>
                <form method="post" class="kt-form" action="{{route('financeiro.update', $dadosBancario->getKey())}}" >
                    @csrf
                    @method('PUT')
                    <div class="kt-portlet__body">
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Municipio</label>
                                    <select required class="form-control kt-select2" id="kt_select2_2" name="municipio">
                                        <option></option>
                                        @if ($dadosBancario->municipio == "Salvador"))
                                            <option value="Salvador" selected="selected">Salvador</option>
                                            <option value="Aracaju">Aracaju</option>
                                        @elseif ($dadosBancario->municipio == "Aracaju"))
                                            <option value="Aracaju" selected="selected">Aracaju</option>
                                            <option value="Salvador">Salvador</option>
                                        @else
                                        <option value="Salvador">Salvador</option>
                                        <option value="Aracaju">Aracaju</option>
                                        @endif
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Nome completo</label>
                                    <input type="text" required class="form-control" name="nome" value="{{ $dadosBancario->nome }}" placeholder="Digite seu nome completo">
                                </div>
                            </div>
                            <div class="col-md-2">
                                <div class="form-group">
                                    <label>CPF</label>
                                    <input type="text" required class="form-control cpf" name="cpf" value="{{ $dadosBancario->cpf }}" placeholder="000.000.000-00">
                                </div>
                            </div>
                            <div class="col-md-2">
                                <div class="form-group">
                                    <label>Pix</label>
                                    <input type="text" required class="form-control" name="pix" value="{{ $dadosBancario->pix }}" placeholder="Insira o pix">
                                </div>
                            </div>
                        </div>                            
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Banco</label>
                                    <select required class="form-control kt-select2" id="kt_select2_1" name="banco_id">
                                        <option></option>
                                        @foreach ($bancos as $banco)
                                            @if ($banco->id == $dadosBancario->banco_id))
                                                <option value="{{$banco->id}}" selected="selected">{{$banco->codigo}}-{{$banco->nome}}</option>
                                            @else
                                                <option value="{{$banco->id}}">{{$banco->codigo}}-{{$banco->nome}}</option>
                                            @endif
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Agencia</label>
                                    <input required class="form-control" type="number" name="agencia" value="{{ $dadosBancario->agencia }}" placeholder="0000">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Conta com digito</label>
                                    <input type="text" required class="form-control conta" name="conta" value="{{ $dadosBancario->conta }}" placeholder="000000-0">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="kt-portlet__foot">
                        <div class="kt-form__actions">
                            <button type="submit" class="btn btn-success">Atualizar</button>
                            <a href="{{route('financeiro.index', ['s' => Crypt::encrypt("s3nh4")])}}" class="btn btn-secondary">Voltar</a>
                        </div>
                    </div>
                </form>
                <!--end::Form-->
            </div>
            <!--end::Portlet-->
        </div>
    </div>
</div>
<!-- end:: Content -->
@endsection
@section('template_fastload_js') 
    $(document).ready(function () {
        $('.cpf').mask('000.000.000-00');
        $('.conta').mask('000000000000-0', {reverse: true});
        $(".kt-form").submit(function() {
            $(".conta").unmask();
        });        
        $('#kt_select2_1').select2({
            placeholder: "Selecione o banco"
        });      
        $('#kt_select2_2').select2({
            placeholder: "Selecione o municipio"
        });
    });
@endsection